### ISSUE TITLE
В названиях пакетов не используется _

### ISSUE THREAD

**Issue by tgurskaya96** [DanikKul/EPAM_Workshop#1]
https://github.com/DanikKul/EPAM_Workshop/blob/140c8754aba9ec0457627eddfc06be256761904a/src/main/java/com/workshop/epam_workshop/counters/Counter.java#L1

**Comment by DanikKul** [comment]
Исправлено. Теперь в названиях пакетов _**epam_workshop**_ заменено на _**EpamWorkshop**_.
