### ISSUE TITLE
Структура очень сложная и запутанная, можно упростить. Подсказка каждому входному параметру соответствуют 2 числа, не нужно под каждое число создавать map.

### ISSUE THREAD

**Issue by tgurskaya96** [DanikKul/EPAM_Workshop#2]
https://github.com/DanikKul/EPAM_Workshop/blob/140c8754aba9ec0457627eddfc06be256761904a/src/main/java/com/workshop/epam_workshop/model/Converter.java#L12

**Comment by DanikKul** [comment]
Не совсем понятно, что вы имели ввиду в подсказке, поскольку изменение структуры _Converter_ изменит вид возвращаемого объекта с помощью _ResponseEntity_.
```
return new ResponseEntity<>(new Converter(value), HttpStatus.OK);
```
Возможным решением является удаление map и представление полей класса как:
```
// class Converter
private final Double meters;
private final Double inches;
private Double userInput;
private static final Logger logger = LogManager.getLogger(Converter.class);
private static final CacheResult cache = new CacheResult();
```
Где _meters_ и _inches_ являются переменными, которые нужно сконвертировать, а _userInput_ показывает какое число быть преобразовано в метры и дюймы. Однако такое решение изменит представление возвращаемого объекта в _ResponseEntity_.
До:
```
// json
{
    "metersToInches": {"inches":472.44,"meters":12.0},
    "inchesToMeters": {"inches":12.0,"meters":0.305},
    "userInput": 12.0
}
```
После:
```
// json
{
    "meters": 0.305,
    "inches": 472.44,
    "userInput": 12.0
}
```
В общем и целом данная структура понятна, но не столь подробна как предыдущая

**Comment by DanikKul** [comment]
Итак, я произвел замену структуры класса _Converter_, убрав оттуда все _HashMap_. Теперь все работает так, как я привел в комментарии выше.

**Comment by tgurskaya96** [comment]
Модель не должна зависеть от представления. Я согласна, что json становится более читаемым.И формировать json можно по тем правилам, по которым хотите в отдельном месте.
В данном случае у вас дублируется информация, число 12 в нескольких местах
