### ISSUE TITLE
Операции Math.round(value * 39.37 * 1000) / 1000. и обратная очень часто повторяются, проведите рефакторинг

### ISSUE THREAD

**Issue by tgurskaya96** [DanikKul/EPAM_Workshop#3]
https://github.com/DanikKul/EPAM_Workshop/blob/140c8754aba9ec0457627eddfc06be256761904a/src/main/java/com/workshop/epam_workshop/model/Converter.java#L32

**Comment by DanikKul** [comment]
Операции конвертации из метров в дюймы и наоборот были занесены в отдельные функции. Надеюсь это то, что вы имели ввиду
