### ISSUE TITLE
Исправлено некорректно, в названиях пакетов используются только маленькие буквы

### ISSUE THREAD

**Issue by tgurskaya96** [DanikKul/EPAM_Workshop#5]
Исправлено. Теперь в названиях пакетов _**epam_workshop**_ заменено на _**EpamWorkshop**_.

_Originally posted by @DanikKul in https://github.com/DanikKul/EPAM_Workshop/issues/1#issuecomment-1482918752_

**Comment by DanikKul** [comment]
Исправлено.
