### ISSUE TITLE
В модели не стоит производить вычислений, отделите логику от модели

### ISSUE THREAD

**Issue by tgurskaya96** [DanikKul/EPAM_Workshop#6]
https://github.com/DanikKul/EPAM_Workshop/blob/44993857a0f611e1b8afbd2622d463be1a5138a7/src/main/java/com/workshop/epamworkshop/model/Converter.java#L8

**Comment by DanikKul** [comment]
Насколько я понимаю, я должен вынести отдельно только две функции: _convertToInches_ и _convertToMeters_?

**Comment by DanikKul** [comment]
Убрал из модели статические методы _convertToInches_, _convertToMeters_, _parseData_, _validateData_. Все они были вынесены в класс ConverterLogic.
